version: '2'

services:
  dbserver:
    image: mysql:5.6
    ports:
      - 13333:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "lab"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
  ciapp1:
    container_name: ciapp1
    image: ciapp:96a676c
    mem_limit: 256m
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbserver/lab?useSSL=false"
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - dbserver # doesn't quite do what you'd hope...
  ciapp2:
      container_name: ciapp2
      image: ciapp:96a676c
      mem_limit: 256m
      environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://dbserver/lab?useSSL=false"
        SPRING_DATASOURCE_USERNAME: test
        SPRING_DATASOURCE_PASSWORD: test
      depends_on:
        - dbserver # doesn't quite do what you'd hope...
  lb:
    container_name: mylb
    image: haproxy:1.9.6
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
      - 1936:1936
    depends_on:
      - ciapp1