version: '2'

services:
  dbserver:
    image: mysql:5.6
    ports:
      - 13333:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "lab"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
  ciapp:
    image: ciapp:40b6b08
    ports:
      - 8080
    mem_limit: 128m
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbserver/lab?useSSL=false"
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - dbserver # doesn't quite do what you'd hope...